# ios-build.yml
# TuneBox
#
# Created by Vadim Sorokolit on 17.06.2026.

name: iOS Build

on:
  push:
    branches:
      - main
      - develop
      - features/downloads-view-model

  pull_request:

jobs:
  build:
    runs-on: xcode-27

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '27.0'

      - name: Build TuneBox
        run: |
          xcodebuild clean build \
          -project TuneBox/TuneBox.xcodeproj \
          -scheme TuneBox \
          -destination 'generic/platform=iOS Simulator' \
          -skipPackagePluginValidation
